### ISSUE TITLE
Asking for a more understandable codes and high resolution graphs

### ISSUE THREAD

**Issue by huseyn-guliyev** [tseyanglim/CovidGlobal#1]
Firstly, thanks for such a wonderful and comprehensive analysis. Research paper also helped us to understand COVID problem. 

While trying to extract relevant analysis for our country, our team couldn't run Jupyter Notebooks because of some libraries and couldn't understand codes completely. We would like to ask you to support more understandable Python or R codes if possible. 

Additionally, we would like to get codes to produce high resolution graphs (interactive graphs would be better) if possible.

Thanks in advance

**Comment by tseyanglim** [comment]
Hi, sorry about any confusion! We were in a hurry to get _some_ version of the code up alongside the pre-print paper even though it wasn't the cleanest. We should have a cleaner version up within the next week or two.

Which libraries / code did you have issue with? Note that running the actually simulations requires [Vensim software](https://vensim.com/), which is a completely separate software (not a Python package) used for system dynamics modelling that the code will call.

Good suggestion re: interactive graphs, we will look into doing that. For now the graphing is done in Matlab; the code for that is in the Results folder [here](https://github.com/tseyanglim/CovidGlobal/blob/master/Results/MakeGraphsV54.m).

**Comment by huseyn-guliyev** [comment]
Great to see that you appreciate our suggestions.

We had problem with `statsmodel.decompose.STL` and `keyboard`. We tried to install, but it didn't work. Having no Vensim Software may cause it as well. 

We would be glad to see graphing and modeling codes in R or Python, since Matlab is not open source, we can't afford it. Would it be possible in next weeks?

Thanks for your reply.

**Comment by tseyanglim** [comment]
Unfortunately the Vensim software is a necessary step to run the model itself. There isn't really any way around that.

For `statsmodels.decompose.STL`, if you're running in Jupyter, you need to make sure that you're loading the most recent version of `statsmodels` (you may need to dig into Anaconda, if you're using that, to make sure it's getting most up-to-date packages) - the STL function was only added in the most recent version.

For `keyboard` you will want to manually install that directly from a notebook, similar to the solutions [here](https://stackoverflow.com/questions/38368318/installing-a-pip-package-from-within-a-jupyter-notebook-not-working) - I'm not sure why but it doesn't work otherwise. That said, `keyboard` is only used to bypass some error messages with Vensim, so if you are trying to run everything except the Vensim calls, you could simply remove all references to the module and it should be fine.

Re: Matlab issue - will see what we can do, I have been meaning to switch graphing to Python but it is relatively low priority at the moment so I don't want to promise anything :)
